/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_orbbec_NativeNI_NativeGestureDetect */

#ifndef _Included_com_orbbec_NativeNI_NativeGestureDetect
#define _Included_com_orbbec_NativeNI_NativeGestureDetect
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_orbbec_NativeNI_NativeGestureDetect
 * Method:    nativeInit
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_orbbec_NativeNI_NativeGestureDetect_nativeInit
  (JNIEnv *, jobject);

/*
 * Class:     com_orbbec_NativeNI_NativeGestureDetect
 * Method:    calibration
 * Signature: (JJI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_orbbec_NativeNI_NativeGestureDetect_calibration
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     com_orbbec_NativeNI_NativeGestureDetect
 * Method:    getNativeGestureResult
 * Signature: (JJJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_orbbec_NativeNI_NativeGestureDetect_getNativeGestureResult
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     com_orbbec_NativeNI_NativeGestureDetect
 * Method:    nativeDestroy
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_orbbec_NativeNI_NativeGestureDetect_nativeDestroy
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
